### ISSUE TITLE
investigate implementing incipit lookup in google sheets

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/pemm-scripts#13]
investigation confirms that:
- we can create new UI elements to host the incipit search (menu, sidebar)
- we can make async calls to a web service (tested w/ github json api)
- we can have the user use fetched data to populate the sheet

**Comment by thatbudakguy** [comment]
one notable consequence of this is that the implementation of the project will change from a ["standalone script" ](https://developers.google.com/apps-script/guides/standalone) to a ["container-bound script"](https://developers.google.com/apps-script/guides/bound), because this is a prerequisite for being able to manipulate the UI of a google sheet.

the major difference is:
- standalone scripts show up in the creator's google drive with a blue icon; they are independent objects that can exist without any relationship to a sheet, doc, etc.
- bound scripts only exist in relation to (or "on") a particular google sheet (or doc, form, etc) and can only be accessed by opening that sheet (the "container").

see [this link](https://developers.google.com/apps-script/guides/bound#special_methods) for more info on what bound scripts can do that standalone scripts cannot.

the implication for us is that you will no longer create new instances of the master data spreadsheet; instead you will create your own sheet and then "point" `clasp` at it and upload the code generated in this repo to install new tools/UI into that sheet. this can be done on sheets that already have data in them.

**Comment by thatbudakguy** [comment]
implementation now tracked on #16.
