### ISSUE TITLE
research and prototype an approach for analyzing order of stories in manuscripts

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/pemm-scripts#69]
Notes from @elambrinaki on Slack:

> Overall, I would love to discuss an approach for testing whether a standard collection existed and how it changed.
> Assume the standard order of stories IDs in a manuscript is known and it is 1-2-3-4-5. We want to analyze how it has been changing over time.
> A manuscript with 1-10-3-4-5 (one miracle substitution), a manuscript with 1-3-2-4-5 (one permutation), a manuscript with 1-2-3-10-11 (one subsequence substitution), a manuscript with 4-5-1-2-3 (one subsequence permutation), do we assign them the same value of "divergence from the canonical set" indicator or different values?
> Another situation is when we want to find the standard order. I think we don't have enough manuscripts to answer it statistically (about 100), but I would love to be wrong.
I believe a quantitative approach to answer these sequence and relations questions has already been invented in the field. I haven't looked up literature yet, so if you know relevant sources, please direct us to them.

--- 

The data isn't quite ready for this analysis yet, but @elambrinaki guesses it will be in a few months; prototype an approach that can be adapted and handed off — perhaps a well-documented jupyter notebook that a student could work from, or an approach in OpenRefine that can be saved and reused.

**Comment by thatbudakguy** [comment]
> A manuscript with 1-10-3-4-5 (one miracle substitution), a manuscript with 1-3-2-4-5 (one permutation), a manuscript with 1-2-3-10-11 (one subsequence substitution), a manuscript with 4-5-1-2-3 (one subsequence permutation), do we assign them the same value of "divergence from the canonical set" indicator or different values?

it seems like if you represent the order of miracles as a sequence of numbers (as you've done here), you can use the [levenshtein edit distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between the sequence and the "canonical sequence" (1-2-3-4-5) to get a quick measure of divergence. for examples you listed:

- 1-10-3-4-5 has an edit distance of **1**
- 1-3-2-4-5 has an edit distance of **2**
- 1-2-3-10-11 has an edit distance of **2**
- 4-5-1-2-3 has an edit distance of **4**

...where a higher number indicates more divergence from the canonical order.

openrefine includes levenshtein as a clustering method, so if you store this numeric sequence in the spreadsheet along with the manuscript, you could ask it to aggregate the manuscripts that have the most similar orders into clusters for you.

there are lots of other ways to calculate edit distance, including some that have "swap" as an option (i think levenshtein just treats it as two substitutions, which you can see in your second example sequence). 

**edit**: the method that allows "swap" (transposition) as an operation is the [damerau-levenshtein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) distance. i think that would let you treat 1-3-2-4-5 as having an edit distance of **1**, since it's one "swap" (2 and 3).

**Comment by elambrinaki** [comment]
Thank you @thatbudakguy! Clustering in OpenRefine is a great idea.

**Comment by kmcelwee** [comment]
First go at chart/stats generation on random data:
https://github.com/kmcelwee/pemm-jupyter/blob/master/Research%20Manuscript%20Order.ipynb

**Comment by kmcelwee** [comment]
Latest analysis has been pushed:
https://github.com/kmcelwee/pemm-jupyter/blob/master/Research%20Manuscript%20Order.ipynb

Later today or in the morning, I'll be setting up a google colab so that permissions / usability / dependencies are better standardized.

Reach out if there are specific research questions that I didn't answer!

**Comment by elambrinaki** [comment]
@kmcelwee Kevin, thank you very much!!
Could you please help me get started. Where can I run the code?

Re the Collocation matrices that show IDs that precede and follow other IDs. I should look at yellow dots on the diagram, right? Is there a way to get the information in a table format? For example, I would select the desired frequency (say, 80%) and have a two-column table with pairs of IDs in which the first ID preceeds the second ID four out of five times it appears in a manuscript.

Also, how do I combine the information from the two collocation matrices (IDs that precede and IDs that follow) to find the pairs of IDs that are often neighbors?

Re testing mss for a canonical sequence. Say, I have a sequence of 33 miracles that is called canonical. I want to see how many mss contain this sequence fully, how many contain it with the Levenshtein edit distance =1, =2, =3, etc. Is that posssible? 
Now assume I want to test a sequence of 70 miracles. Suppose some mss have only 50 miracles, but their order matches the order of the first 50 miracles in the sequence of 70 being tested. Are they counted someway as the ones that contain the desired sequence?

Finally, is there a way to see a pattern in the data about the sequence of miracles? Is it possible not to test against a specific sequence, but to find such sequence in the data? To get something like: 17-84-3-193-5 is the sequence of miracles that is present in 80% of mss.

**Comment by kmcelwee** [comment]
> Could you please help me get started. Where can I run the code?

- [x] I will be migrating to Google Colab, a platform that allows you to run python code in your web browser. I will share the link when I’ve finished migrating

> Re the Collocation matrices that show IDs that precede and follow other IDs. I should look at yellow dots on the diagram, right? Is there a way to get the information in a table format? For example, I would select the desired frequency (say, 80%) and have a two-column table with pairs of IDs in which the first ID preceeds the second ID four out of five times it appears in a manuscript.

- [x] I will turn collocation matrices into CSVs.
- [x] I will highlight the highest numbers that aren’t diagonal.

> Also, how do I combine the information from the two collocation matrices (IDs that precede and IDs that follow) to find the pairs of IDs that are often neighbors?

- [x] I will list the most popular sequences of length K that aren’t contiguous. So to see the most common pairs, we'll set K=2

> Re testing mss for a canonical sequence. Say, I have a sequence of 33 miracles that is called canonical. I want to see how many mss contain this sequence fully, how many contain it with the Levenshtein edit distance =1, =2, =3, etc. Is that posssible?
> 
> Now assume I want to test a sequence of 70 miracles. Suppose some mss have only 50 miracles, but their order matches the order of the first 50 miracles in the sequence of 70 being tested. Are they counted someway as the ones that contain the desired sequence?

Because this is a would require custom user input to get a statistical output, it is largely out of scope. While, yes, this query is possible to program, there’s not a straightforward way to make it user-friendly to non-programmers. 

> Finally, is there a way to see a pattern in the data about the sequence of miracles? Is it possible not to test against a specific sequence, but to find such sequence in the data? To get something like: 17-84-3-193-5 is the sequence of miracles that is present in 80% of mss.

I can give you the most common non-contiguous sequences of a given length. (See checklist item above)

**Comment by rlskoeser** [comment]
@kmcelwee thanks for all this work, it's cool to see some preliminary analysis of the data.

I noticed you are cloning the whole git repository to get the data file; wouldn't it be simpler to reference the current version of the CSV file from the git repository by URL ? 

Some of your comments in the notebook reference the "ideal" order, what do you mean by this? 

I see your comments about creating a unique integer id, but I don't understand why this matters. Would you explain?

FYI, your list of stories that appear first more than once doesn't include canonical story ids.

How much work would it be to generate something like a heatmap of where each story ever / most often occurs within the sequence in a given manuscript, either by count or (perhaps more useful) by percentage within a sequence? (i.e. story x most often occurs 3rd but also shows up first, 5th, 6th, 13th, etc).

**Comment by rlskoeser** [comment]
On the unique integer id — am I right that you're using that to sort on canonical id? I'm not sure the order of canonical ids is actually meaningful, we'd need to ask Wendy about that.

**Comment by kmcelwee** [comment]
> I noticed you are cloning the whole git repository to get the data file; wouldn't it be simpler to reference the current version of the CSV file from the git repository by URL ?

Good point! When I had written that code, I didn't know if I would need the whole data set. 

- [x] Replace git clone with a url request

> Some of your comments in the notebook reference the "ideal" order, what do you mean by this? ... On the unique integer id — am I right that you're using that to sort on canonical id? I'm not sure the order of canonical ids is actually meaningful, we'd need to ask Wendy about that.

That was just an assumption provided by Evgeniia in the research question. I use the functions like `is_continuous` and `is_reordered`, which assumes that there is some kind of "correct" order. This definitely warrants a larger discussion, but I'm not sure how to best develop an action item in response to this.

And yes, sorting by "1-A" and "600L" became a headache, so I made a continuous integer ID and mapped between them when necessary. If you have a better idea let me know!

> FYI, your list of stories that appear first more than once doesn't include canonical story ids.

- [x] Thank you, I'll add this.

> How much work would it be to generate something like a heatmap of where each story ever / most often occurs within the sequence in a given manuscript, either by count or (perhaps more useful) by percentage within a sequence? (i.e. story x most often occurs 3rd but also shows up first, 5th, 6th, 13th, etc).

I thought about this, but because the manuscripts are of different lengths, the graphic might be misleading. If you are interested anyway, it'd take ~30 minutes to throw together. Let me know!

**Comment by rlskoeser** [comment]
> I thought about this, but because the manuscripts are of different lengths, the graphic might be misleading. If you are interested anyway, it'd take ~30 minutes to throw together. Let me know!

Right, that was my concern about length. Would using percentages mitigate? i.e. some stories are always in the first half (third, quarter, whatever) of a sequence, others always show up towards the end of a sequence?

**Comment by kmcelwee** [comment]
Wow, you had said that explicitly, I'm sorry I skimmed over that. Yes, I will look into how to create some kind of percentage-based approach. Granted, because it's continuous, it'll have to be some kind of heatmap-histogram, and I've never done that before, but I'll try that out! 

- [x] heatmap histogram

**Comment by rlskoeser** [comment]
> That was just an assumption provided by Evgeniia in the research question. I use the functions like `is_continuous` and `is_reordered`, which assumes that there is some kind of "correct" order. This definitely warrants a larger discussion, but I'm not sure how to best develop an action item in response to this.

My understanding of the research question is that there isn't a "correct" order per se, but there might be an order (or some set of sequences) that are very common, and they would like to figure out what that is. I think maybe the work you added on most common non-contiguous sequences might be getting at this question — how hard to expand and just find the most common sequences?

**Comment by kmcelwee** [comment]
It's just removing an if-statement!
- [x] Remove if-statement that drops contiguous sequences when finding the most common K-grams

I'm sorry for the misunderstanding, these are the sections that rely on the assumption that there is a "proper" order:
* "What is the distribution of the Levenshtein edit distances?"
* "Can we categorize the different permutations?"

Let me know if there's a certain way you think it's best to recharacterize these questions

**Comment by kmcelwee** [comment]
I have updated the Jupyter notebook with the new heatmap and the other small chores. To help remove some of the noise, I've assigned two thresholds that filter out manuscripts with fewer than 5 stories and stories with fewer than 5 appearances. These constants can be changed if necessary.

I've moved this notebook into Google colab. I've realized some long-term headaches that will come if we want to use Colab more consistently, and @rlskoeser, I'll collect my thoughts after lunch, but for now, this should work fine. Here is the link:

https://colab.research.google.com/drive/1SXDB0e2PyALBY-QPTZ4nspXS41cTQKFP?usp=sharing

I think I've addressed all of the checklist items I've put together from the conversation above. Let me know if I missed anything!

**Comment by elambrinaki** [comment]
@rlskoeser @kmcelwee Thank you very much for the analysis and discussion!
I confirm what Rebecca is saying: the order of stories we are testing is not continuos. The canonical set of 33 miracles is 
13, 187, 161, 162, 163, 19, 27, 33, 54, 153, 154, 16, 46, 43, 48, 59, 57, 61, 68, 82, 83, 99, 103, 112, 158, 140, 142, 7, 125, 152, 148, 236, 207. It is well-known, so we won't make any discovery by finding this pattern in our data. We will still compute the percentage of manuscripts that have this sequence intact and with different edits (substitutions/permutations/subsequence substitutions/subsequence permutations), and we will almost certainly find that a lot of them do. However, the main focus is on finding other sequences that are common. We will use the "most popular sequences of length K" code for that. In the ideal world, it would be great to also be able to see some common sequences _with small differences_ from each other (a couple of IDs out of order or added/subtracted), not only the exact sequences of length K.

**Comment by thatbudakguy** [comment]
> The canonical set of 33 miracles

@elambrinaki just a question for my own understanding: is this set canonical in terms of its order, or just its membership? that is, is the order you listed also the canonical order, or is there no such thing as a canonical order - only a collection that includes the miracles listed above?

@kmcelwee there's [this python-levenshtein](https://pypi.org/project/python-Levenshtein/) package which I have used that makes the computation much easier - you can just say `Levenshtein.ratio()` to get a measure of similarity between two strings/sequences. however, it relies on some C code to speed it up, so I'm not sure what would happen in the context of a colab notebook. maybe still worth trying?

**Comment by WendyLBelcher** [comment]
Re the canonical set of 33 miracles. @elambrinaki has been working on this, so what I say here is before her analysis finds. This is always said, that these 33 miracles are canonical (appear in most all manuscripts), but we want to see if it is true. I believe it is canonical in membership, but I suspect it is simply those stories that are most often illustrated. Lots of stories are common and not illustrated. I don't know if there is a standard order, but I know Eyob says there is.

**Comment by kmcelwee** [comment]
My action items from today's conversations:

- [x] 8 and 252 are shown to occur early in manuscripts, but that doesn't seem to be the case
- [x] Move analyses away from the incorrect assumptions about order
- [x] Try out Cython's Levenshtein.ratio()

**Comment by elambrinaki** [comment]
@thatbudakguy @WendyLBelcher  I should have said the canonical sequence. These 33 miracles appear in mss often and often in this order.
Many sequences of length 10 Kevin shown today are the pieces of this canonical sequence. Some mss in our database have this canonical sequence in perfect order, some with edits. 

Another Macomber hypothesis is about an early collection from the time of Zar'a Ya'eqob (1400s) that included IDs 135 to 206 in chronological order. The early mss in the dataset often include unbroken subsequences of 135-206 in chronological order (e.g. 144-147, 149-169, 174-187).

**Comment by kmcelwee** [comment]
I think I've finished our latest action items. The latest version of the notebook can be found here on google colab: 

https://colab.research.google.com/drive/1yRdN4dQtJJou1hJPJyEGVG7IfOkWwlO5?usp=sharing

As @elambrinaki and @thatbudakguy discovered, I had mislabeled the y-axis in the heatmap of story location. It's fixed in the latest update. And while I have put time into triple checking myself, there's still a possibility that I've made an error elsewhere, so always be skeptical of these charts.

With @rlskoeser's suggestion, I've made a heatmap comparing edit distances between manuscripts. It was large, so I tried out an interactive component where a user can see the heatmap value by hovering over the graph. "z" here is the Levenshtein Edit distance between the two manuscripts.

![Screen Shot 2020-07-02 at 10.47.53 AM.png](https://images.zenhubusercontent.com/5e9efff74d7b4923426b5c0d/f808973f-61fc-47a2-ae4b-7d10298aa749)

I think that—save a disastrous error—this issue is safe to close. I'm going to move away from this notebook and towards our other end-of-project commitments. Let me know if that's a problem!

**Comment by rlskoeser** [comment]
@elambrinaki @WendyLBelcher do you want to take a look at Kevin's colab notebook linked above to see if you have any important questions or concerns that he needs to address in the code? 

We included it on the meeting agenda for next week to discuss briefly to make sure you're comfortable working from this as a starting point when the data is ready for this kind of analysis, but we'd prefer to close the issue sooner than that.

**Comment by WendyLBelcher** [comment]
I think because I wasn't tracking what was happening on Github, I'm coming to this completely fresh. It's extremely cool to see all this information depicted graphically!! Wow! So, my first question is if I wanted a jpg of these visuals, could I get them? I can't do screenshots as they are too big and couldn't figure out how to download otherwise. Second, I apologize if this has already been addressed, @elambrinaki likely knows, but are we using manuscripts that have x stories or more? The shorter ones are less standard. Third, I shouldn't comment on what would be easier to read (such as, it would be good to have numbers across the top of the chart "How many story instances are in each manuscript?" rather than at the bottom)?  Fourth, re "What are the Levenshtein edit distances between manuscripts?" the more purple it is, the more similar they are to some standard, the more yellow, the farther? Fifth, can we order the Count of Individual Stories from highest to lowest, rather than by the ID no.? Sixth, I didn't understand the number on the left in "What are the most popular sequences of length K?" @kmcelwee @rlskoeser

**Comment by kmcelwee** [comment]
I'm happy that you find these useful 😁I always find that making data visualizations and answering statistical questions are the most rewarding parts of compiling a dataset.  Hopefully as your dataset becomes more robust, you and other researchers can find other useful trends!

> So, my first question is if I wanted a jpg of these visuals, could I get them? I can't do screenshots as they are too big and couldn't figure out how to download otherwise.

I saved all the charts as a png (along with other useful data), available on the folder icon on the left side of the screen:

![Screen Shot 2020-07-02 at 12.28.30 PM.png](https://images.zenhubusercontent.com/5e9efff74d7b4923426b5c0d/5463b69c-8773-4ac1-958a-285c4a53a794)

Also, left click on the image in your browser, and you should be able to "save image"

> I apologize if this has already been addressed, @elambrinaki likely knows, but are we using manuscripts that have x stories or more? The shorter ones are less standard.

I currently filter out shorter manuscripts only in the final section: "Where does each story fall within the manuscript?" My threshold (`MANUSCRIPT_THRESHOLD`) is currently 5. In that section I've also set a threshold w/r/t stories as well. I only consider story IDs that occur more than 5 times. These are arbitrary, so please tell me if there's a hard cutoff you'd prefer that I can apply to all charts. 

> Third, I shouldn't comment on what would be easier to read (such as, it would be good to have numbers across the top of the chart "How many story instances are in each manuscript?" rather than at the bottom)?

Yes! great suggestion — fixed that on the two tall charts

> Fourth, re "What are the Levenshtein edit distances between manuscripts?" the more purple it is, the more similar they are to some standard, the more yellow, the farther?

Correct! I can cover this more indepth if you'd like to discuss it at our next meeting

> Fifth, can we order the Count of Individual Stories from highest to lowest, rather than by the ID no.? 

Yes, it's very straightforward. It's now changed on the document.

> Sixth, I didn't understand the number on the left in "What are the most popular sequences of length K?"

This is difficult to explain in words and perhaps it's easiest to discuss it in our next meeting for better clarification.  I'm borrowing an idea from NLP called "n-grams".  Here is a youtube video that explains it visually. https://www.youtube.com/watch?v=E_mN90TYnlg 

There's nothing sacred about this approach, but it can help give you an idea of what stories are often paired together.

**Comment by kmcelwee** [comment]
I've uploaded the useful jupyter notebooks to the drive here: 
https://drive.google.com/drive/folders/1qfD61KABd_IgmEH37ZXNNm2BAGl1-N-O

Feel free to click "Open with Colab" on the notebooks in this github repository https://github.com/kmcelwee/pemm-jupyter if you'd like to make a personal copy and experiment.
