### ISSUE TITLE
Body of Story Start column position and validation

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#71]
In our stories, there are two beginnings: the beginning of _the whole miracle_, which includes the blessings and praise to Mary ("A miracle of Our Holy Lady, Virgin in two ways, Mary, Bearer of God..."), and the beginning of the _story account_ ("There was a pious monk...").

Our original plan was to use 1) the beginning of the _miracle_ to record the _folio, column, line_, and 2) the beginning of the _story account_ to record a couple of the first _unique sentences_ of the miracle (the folio/column/line starts are needed for story length calculations, and the unique sentences are used in the Incipit Search Tool to assign story IDs). Later we decided to record the folio, column, line start of the story account as well. It makes our records more precise as we add information about where the incipit comes from, and it makes it easier for people to remember what line to record where.

However, the column Body of Story Start is far away from the Folio/Column/Line Start columns so the catalogers either don't fill it out or waste time on scrolling to it. It would be very helpful to have the columns in the following order:
Folio Start, Column Start, Line Start, **Body of Story Start**, Folio End, Column End, Line End.

Another question is whether to set validation for the Body of Story Start. One might record it as 1ra l. 5 ("1ra" for folio 1r column 1, "l. 5" for line 5), another as 1r,1,5 (merged folio, colum, line numbers). I think it would be better to let the catalogers to use the format they are used to. But this would mean there will be multiple formats in the Body of Story Start field. I am wondering what is your opinion on that.

---

## dev notes
- [x] add **Body of Story Start** to Story instance between Line Start and Folio End as a text field
- [x] add to validation schema
- [x] add deploy notes to document manual step needed when applying new schema

**Comment by rlskoeser** [comment]
Adding this where you suggest makes sense, I can see how otherwise it is unlikely to get filled in. If you want to let the catalogers use their preferred format and just want this recorded so you can refer to it, that seems ok to me — you won't be able to do any calculations based on them, but maybe you could standardize them in OpenRefine later on when the cataloging is complete. If you go that route, I don't think we should try to apply any validation.

The other alternative that occurs to me is to break out body start folio, column, and line into separate fields the way the main start and end are now — this would make them much easier to validate and make it possible to do calculations.  I think you all need to determine what is more important to you: is it more important to have standardized input that can be used for calculations later on? Or is it more important to have something that the catalogers can easily jot down in their preferred format?

**Comment by elambrinaki** [comment]
To make it easier for catalogers is more important. Let's leave this field without validation then. Thank you very much for sharing your opinion.

**Comment by kmcelwee** [comment]
@rlskoeser Safe to close?
